### ISSUE TITLE
Improve panel/view/style.scss

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-treeping#4]
- [x] Reuse css classes from this file src/shared/theme/mixins.scss
- [x] Move css classes to more appropriate levels (it looks some .css classes are not exclusive to panel / view / style.css)
- [x] Use variable instead of #696969 
- [x] Include dummy image (Right now it's just a blank square, it might be better to have a dummy image]

**Comment by ale-romo** [comment]
Item 2 of this list would imply componentizing the elements that exists within /view. I regard such situation outside of the scope of this issue.
